// ── StrategyBacktester.jsx ────────────────────────────────────────────────────
// MarketMind AI — Quant Strategy Backtester
// Rule Builder · Python-computed results · Equity Curve · Trade Log
// ─────────────────────────────────────────────────────────────────────────────

import { useState, useMemo } from "react";
import {
  ComposedChart, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, ReferenceLine, Area, AreaChart, Legend,
} from "recharts";
import {
  FlaskConical, Play, Plus, Trash2, TrendingUp, TrendingDown,
  AlertTriangle, CheckCircle2, Activity, Target, BarChart2,
  Clock, DollarSign, Percent, ChevronDown, ChevronUp,
  ArrowUpRight, ArrowDownRight, Zap, Shield, Star,
} from "lucide-react";

// ── DESIGN TOKENS ─────────────────────────────────────────────────────────────
const T = {
  bg:"#0f172a", surface:"#111827", panel:"#1a2235", card:"#1e2d45",
  border:"#243044", border2:"#2d3f5f", text:"#f1f5f9", sub:"#94a3b8", muted:"#4b6080", dim:"#1e2d3d",
  cyan:"#06b6d4", blue:"#3b82f6", indigo:"#6366f1", violet:"#8b5cf6",
  emerald:"#10b981", green:"#22c55e", red:"#ef4444", rose:"#f43f5e",
  amber:"#f59e0b", orange:"#f97316",
};

// ── PRE-COMPUTED BACKTEST RESULTS (Python engine output) ──────────────────────
// Generated by backtest_engine.py using reliance_data.csv (252 trading days)
// Initial capital: ₹1,00,000 | Asset: RELIANCE | Period: Jun 2023 – Mar 2024
const PRESET_RESULTS = {
  "RSI Oversold": {
    rules: [
      { indicator:"RSI", condition:"<", value:35, action:"BUY" },
      { indicator:"RSI", condition:">", value:65, action:"SELL" },
    ],
    metrics: {
      net_profit:8296.5, net_profit_pct:8.30, buy_hold_ret:9.68,
      win_rate:50.0, total_trades:2, wins:1, losses:1,
      max_drawdown:18.44, sharpe:0.691,
      avg_win:10481.25, avg_loss:-2184.75, profit_factor:4.797,
      initial_capital:100000, final_equity:108296.5,
      start_date:"2023-06-09", end_date:"2024-03-19",
    },
    trades:[
      {entry_date:"2023-06-27",exit_date:"2023-07-12",entry_price:2187.76,exit_price:2431.51,shares:43,pnl:10481.25,pnl_pct:11.14,result:"WIN"},
      {entry_date:"2023-08-24",exit_date:"2024-02-14",entry_price:2308.80,exit_price:2260.25,shares:45,pnl:-2184.75,pnl_pct:-2.10,result:"LOSS"},
    ],
    equity_curve:[
      {date:"Jun-09",strategy:100000,buyhold:100000,rsi:44.5},{date:"Jun-23",strategy:100000,buyhold:98529,rsi:41.9},
      {date:"Jun-27",strategy:100000,buyhold:95857,rsi:34.9},{date:"Jul-05",strategy:105757,buyhold:101722,rsi:53.5},
      {date:"Jul-12",strategy:110481,buyhold:106088,rsi:64.3},{date:"Jul-21",strategy:110481,buyhold:109014,rsi:67.9},
      {date:"Aug-04",strategy:110481,buyhold:105971,rsi:52.3},{date:"Aug-16",strategy:110481,buyhold:110690,rsi:62.3},
      {date:"Aug-24",strategy:110481,buyhold:101160,rsi:35.0},{date:"Sep-01",strategy:120740,buyhold:111149,rsi:61.7},
      {date:"Sep-15",strategy:117591,buyhold:108083,rsi:50.5},{date:"Oct-03",strategy:114810,buyhold:105375,rsi:41.7},
      {date:"Oct-31",strategy:117842,buyhold:108327,rsi:58.9},{date:"Nov-22",strategy:110853,buyhold:101522,rsi:32.1},
      {date:"Dec-06",strategy:102413,buyhold:93305,rsi:22.7},{date:"Dec-22",strategy:99727,buyhold:90689,rsi:28.4},
      {date:"Jan-11",strategy:105368,buyhold:96182,rsi:60.3},{date:"Jan-25",strategy:103250,buyhold:94120,rsi:48.4},
      {date:"Feb-08",strategy:106715,buyhold:97493,rsi:61.9},{date:"Feb-14",strategy:108297,buyhold:99033,rsi:66.1},
      {date:"Feb-20",strategy:108297,buyhold:103556,rsi:76.6},{date:"Mar-07",strategy:108297,buyhold:103882,rsi:63.1},
      {date:"Mar-19",strategy:108297,buyhold:109684,rsi:74.5},
    ],
  },
  "MACD Cross": {
    rules: [
      { indicator:"MACD", condition:">", value:0, action:"BUY" },
      { indicator:"MACD", condition:"<", value:0, action:"SELL" },
    ],
    metrics: {
      net_profit:-2805.92, net_profit_pct:-2.81, buy_hold_ret:9.68,
      win_rate:28.57, total_trades:7, wins:2, losses:5,
      max_drawdown:18.02, sharpe:-0.176,
      avg_win:6017.35, avg_loss:-2968.12, profit_factor:0.811,
      initial_capital:100000, final_equity:97194.08,
      start_date:"2023-06-09", end_date:"2024-03-19",
    },
    trades:[
      {entry_date:"2023-06-20",exit_date:"2023-06-23",entry_price:2334.15,exit_price:2248.75,shares:40,pnl:-3416.0,pnl_pct:-3.66,result:"LOSS"},
      {entry_date:"2023-07-04",exit_date:"2023-08-23",entry_price:2314.13,exit_price:2358.75,shares:39,pnl:1740.18,pnl_pct:1.93,result:"WIN"},
      {entry_date:"2023-08-31",exit_date:"2023-10-03",entry_price:2479.5,exit_price:2405.0,shares:37,pnl:-2756.5,pnl_pct:-3.0,result:"LOSS"},
      {entry_date:"2023-10-31",exit_date:"2023-11-22",entry_price:2472.38,exit_price:2317.05,shares:36,pnl:-5591.88,pnl_pct:-6.28,result:"LOSS"},
      {entry_date:"2024-01-17",exit_date:"2024-01-18",entry_price:2163.6,exit_price:2133.83,shares:39,pnl:-1161.03,pnl_pct:-1.38,result:"LOSS"},
      {entry_date:"2024-01-19",exit_date:"2024-01-29",entry_price:2180.79,exit_price:2130.39,shares:38,pnl:-1915.2,pnl_pct:-2.31,result:"LOSS"},
      {entry_date:"2024-02-08",exit_date:"2024-03-19",entry_price:2225.11,exit_price:2503.34,shares:37,pnl:10294.51,pnl_pct:12.5,result:"WIN"},
    ],
    equity_curve:[
      {date:"Jun-09",strategy:100000,buyhold:100000,rsi:44.5},{date:"Jun-21",strategy:99093,buyhold:101278,rsi:51.2},
      {date:"Jun-23",strategy:96584,buyhold:98529,rsi:41.9},{date:"Jul-05",strategy:96055,buyhold:100800,rsi:50.7},
      {date:"Jul-21",strategy:103366,buyhold:109014,rsi:67.9},{date:"Aug-04",strategy:100658,buyhold:105971,rsi:52.3},
      {date:"Aug-16",strategy:104859,buyhold:110690,rsi:62.3},{date:"Aug-24",strategy:98324,buyhold:101160,rsi:35.0},
      {date:"Sep-01",strategy:100444,buyhold:111149,rsi:61.7},{date:"Sep-19",strategy:96781,buyhold:106811,rsi:46.8},
      {date:"Oct-03",strategy:95568,buyhold:105375,rsi:41.7},{date:"Oct-31",strategy:95568,buyhold:108327,rsi:58.9},
      {date:"Nov-22",strategy:89976,buyhold:101522,rsi:32.1},{date:"Dec-06",strategy:89976,buyhold:93305,rsi:22.7},
      {date:"Jan-09",strategy:89976,buyhold:92589,rsi:45.4},{date:"Jan-17",strategy:89976,buyhold:94798,rsi:52.8},
      {date:"Jan-29",strategy:86900,buyhold:93343,rsi:45.5},{date:"Feb-08",strategy:86900,buyhold:97493,rsi:61.9},
      {date:"Feb-20",strategy:92019,buyhold:103556,rsi:76.6},{date:"Mar-07",strategy:92295,buyhold:103882,rsi:63.1},
      {date:"Mar-19",strategy:97194,buyhold:109684,rsi:74.5},
    ],
  },
  "SMA 20/50": {
    rules: [
      { indicator:"SMA20", condition:">", value:0, action:"BUY (Price > SMA20)" },
      { indicator:"RSI",   condition:">", value:72, action:"SELL" },
    ],
    metrics: {
      net_profit:8341.01, net_profit_pct:8.34, buy_hold_ret:9.68,
      win_rate:75.0, total_trades:4, wins:3, losses:1,
      max_drawdown:18.37, sharpe:0.605,
      avg_win:2780.34, avg_loss:0, profit_factor:999,
      initial_capital:100000, final_equity:108341.01,
      start_date:"2023-06-09", end_date:"2024-03-19",
    },
    trades:[
      {entry_date:"2023-06-09",exit_date:"2024-02-19",entry_price:2282.32,exit_price:2323.9,shares:41,pnl:1704.78,pnl_pct:1.82,result:"WIN"},
      {entry_date:"2024-02-20",exit_date:"2024-02-21",entry_price:2363.48,exit_price:2415.99,shares:40,pnl:2100.4,pnl_pct:2.22,result:"WIN"},
      {entry_date:"2024-02-22",exit_date:"2024-03-18",entry_price:2367.74,exit_price:2478.37,shares:41,pnl:4535.83,pnl_pct:4.67,result:"WIN"},
      {entry_date:"2024-03-19",exit_date:"2024-03-19",entry_price:2503.34,exit_price:2503.34,shares:41,pnl:0,pnl_pct:0,result:"LOSS"},
    ],
    equity_curve:[
      {date:"Jun-09",strategy:100000,buyhold:100000,rsi:44.5},{date:"Jun-23",strategy:98624,buyhold:98529,rsi:41.9},
      {date:"Jul-05",strategy:101612,buyhold:101723,rsi:53.5},{date:"Jul-21",strategy:108435,buyhold:109014,rsi:67.9},
      {date:"Aug-04",strategy:105587,buyhold:105971,rsi:52.3},{date:"Aug-16",strategy:110003,buyhold:110690,rsi:62.3},
      {date:"Aug-24",strategy:101086,buyhold:101160,rsi:35.0},{date:"Sep-01",strategy:110433,buyhold:111149,rsi:61.7},
      {date:"Sep-19",strategy:106374,buyhold:106811,rsi:46.8},{date:"Oct-03",strategy:105030,buyhold:105375,rsi:41.7},
      {date:"Oct-31",strategy:107792,buyhold:108327,rsi:58.9},{date:"Nov-22",strategy:101424,buyhold:101522,rsi:32.1},
      {date:"Dec-06",strategy:93735,buyhold:93305,rsi:22.7},{date:"Jan-09",strategy:93065,buyhold:92589,rsi:45.4},
      {date:"Jan-25",strategy:94497,buyhold:94120,rsi:48.4},{date:"Feb-08",strategy:97654,buyhold:97493,rsi:61.9},
      {date:"Feb-20",strategy:101705,buyhold:103556,rsi:76.6},{date:"Mar-07",strategy:103936,buyhold:103882,rsi:63.1},
      {date:"Mar-19",strategy:108341,buyhold:109684,rsi:74.5},
    ],
  },
  "BB Reversal": {
    rules: [
      { indicator:"RSI", condition:"<", value:30, action:"BUY" },
      { indicator:"RSI", condition:">", value:60, action:"SELL" },
    ],
    metrics: {
      net_profit:-1148.2, net_profit_pct:-1.15, buy_hold_ret:9.68,
      win_rate:66.67, total_trades:9, wins:6, losses:3,
      max_drawdown:3.03, sharpe:-0.346,
      avg_win:606.28, avg_loss:-1595.29, profit_factor:0.76,
      initial_capital:100000, final_equity:98851.8,
      start_date:"2023-06-09", end_date:"2024-03-19",
    },
    trades:[
      {entry_date:"2023-11-24",exit_date:"2023-11-27",entry_price:2271.46,exit_price:2295.09,shares:41,pnl:968.83,pnl_pct:1.04,result:"WIN"},
      {entry_date:"2023-11-28",exit_date:"2023-11-29",entry_price:2256.51,exit_price:2279.65,shares:42,pnl:971.88,pnl_pct:1.03,result:"WIN"},
      {entry_date:"2023-12-05",exit_date:"2023-12-06",entry_price:2192.76,exit_price:2129.51,shares:44,pnl:-2783.0,pnl_pct:-2.88,result:"LOSS"},
      {entry_date:"2023-12-07",exit_date:"2023-12-08",entry_price:2113.9,exit_price:2117.91,shares:44,pnl:176.44,pnl_pct:0.19,result:"WIN"},
      {entry_date:"2023-12-11",exit_date:"2023-12-12",entry_price:2127.67,exit_price:2133.4,shares:44,pnl:252.12,pnl_pct:0.27,result:"WIN"},
      {entry_date:"2023-12-13",exit_date:"2023-12-14",entry_price:2117.92,exit_price:2130.66,shares:44,pnl:560.56,pnl_pct:0.6,result:"WIN"},
      {entry_date:"2023-12-18",exit_date:"2023-12-19",entry_price:2084.46,exit_price:2100.19,shares:45,pnl:707.85,pnl_pct:0.75,result:"WIN"},
      {entry_date:"2023-12-20",exit_date:"2023-12-21",entry_price:2082.84,exit_price:2055.01,shares:46,pnl:-1280.18,pnl_pct:-1.34,result:"LOSS"},
      {entry_date:"2023-12-22",exit_date:"2023-12-25",entry_price:2069.82,exit_price:2053.76,shares:45,pnl:-722.7,pnl_pct:-0.78,result:"LOSS"},
    ],
    equity_curve:[
      {date:"Jun-09",strategy:100000,buyhold:100000,rsi:44.5},{date:"Jul-21",strategy:100000,buyhold:109014,rsi:67.9},
      {date:"Aug-16",strategy:100000,buyhold:110690,rsi:62.3},{date:"Sep-01",strategy:100000,buyhold:111149,rsi:61.7},
      {date:"Oct-03",strategy:100000,buyhold:105375,rsi:41.7},{date:"Oct-31",strategy:100000,buyhold:108327,rsi:58.9},
      {date:"Nov-22",strategy:100000,buyhold:101522,rsi:32.1},{date:"Nov-24",strategy:100000,buyhold:99524,rsi:27.7},
      {date:"Nov-28",strategy:100969,buyhold:98869,rsi:29.2},{date:"Nov-30",strategy:101941,buyhold:98401,rsi:30.7},
      {date:"Dec-04",strategy:101941,buyhold:98186,rsi:31.4},{date:"Dec-06",strategy:99158,buyhold:93305,rsi:22.7},
      {date:"Dec-08",strategy:99334,buyhold:92796,rsi:22.7},{date:"Dec-14",strategy:100147,buyhold:93355,rsi:28.1},
      {date:"Dec-18",strategy:100147,buyhold:91331,rsi:25.1},{date:"Dec-22",strategy:99575,buyhold:90689,rsi:28.4},
      {date:"Dec-26",strategy:98852,buyhold:91460,rsi:34.7},{date:"Jan-11",strategy:98852,buyhold:96182,rsi:60.3},
      {date:"Feb-08",strategy:98852,buyhold:97493,rsi:61.9},{date:"Mar-07",strategy:98852,buyhold:103882,rsi:63.1},
      {date:"Mar-19",strategy:98852,buyhold:109684,rsi:74.5},
    ],
  },
};

// ── INDICATOR & CONDITION OPTIONS ─────────────────────────────────────────────
const INDICATORS = ["RSI","SMA20","SMA50","EMA9","MACD","BB Upper","BB Lower","Price","Volume"];
const CONDITIONS = ["<",">","<=",">=","=="];
const ACTIONS    = ["BUY","SELL"];

const INDICATOR_DEFAULTS = {
  RSI:30, SMA20:2300, SMA50:2200, EMA9:2300,
  MACD:0, "BB Upper":2600, "BB Lower":2100, Price:2400, Volume:500000,
};

const INDICATOR_DESC = {
  RSI: "Relative Strength Index (0-100)",
  SMA20: "20-day Simple Moving Average",
  SMA50: "50-day Simple Moving Average",
  EMA9:  "9-day Exponential Moving Average",
  MACD:  "MACD Line (12-26-9)",
  "BB Upper": "Bollinger Band Upper (20,2)",
  "BB Lower": "Bollinger Band Lower (20,2)",
  Price: "Current close price",
  Volume: "Daily traded volume",
};

// ── MINI PRIMITIVES ────────────────────────────────────────────────────────────
const Card = ({children, style}) => (
  <div style={{background:T.card,border:`1px solid ${T.border}`,borderRadius:12,padding:"14px 16px",...style}}>
    {children}
  </div>
);

const SH = ({icon:Icon,title,right,color=T.cyan}) => (
  <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:11}}>
    <div style={{display:"flex",alignItems:"center",gap:6}}>
      {Icon&&<Icon size={13} color={color} strokeWidth={2.5}/>}
      <span style={{fontSize:9.5,fontWeight:900,color,letterSpacing:"0.12em",textTransform:"uppercase"}}>{title}</span>
    </div>
    {right}
  </div>
);

const Badge = ({children,color=T.cyan,style}) => (
  <span style={{fontSize:8,fontWeight:800,padding:"2px 7px",borderRadius:4,
    background:color+"22",color,border:`1px solid ${color}44`,letterSpacing:"0.04em",...style}}>
    {children}
  </span>
);

const MiniBar = ({value,max=100,color=T.cyan,height=5}) => (
  <div style={{width:"100%",height,background:T.border,borderRadius:3,overflow:"hidden"}}>
    <div style={{height,width:`${Math.min(100,(value/max)*100)}%`,background:color,borderRadius:3,transition:"width 0.8s"}}/>
  </div>
);

// ── METRIC CARD ────────────────────────────────────────────────────────────────
function MetricCard({label, value, sub, color, Icon, trend}) {
  return (
    <div style={{background:T.panel,border:`1px solid ${T.border2}`,borderRadius:10,padding:"12px 14px",position:"relative",overflow:"hidden"}}>
      <div style={{position:"absolute",top:0,right:0,width:48,height:48,
        background:`radial-gradient(circle at top right, ${color}18, transparent)`,borderRadius:"0 10px 0 0"}}/>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:6}}>
        <span style={{fontSize:7.5,color:T.muted,fontWeight:800,letterSpacing:"0.1em",textTransform:"uppercase"}}>{label}</span>
        {Icon && <Icon size={14} color={color} opacity={0.7}/>}
      </div>
      <div style={{fontSize:22,fontWeight:900,color,lineHeight:1,marginBottom:3}}>{value}</div>
      {sub && <div style={{fontSize:8,color:T.muted}}>{sub}</div>}
      {trend!==undefined && (
        <div style={{display:"flex",alignItems:"center",gap:3,marginTop:4}}>
          {trend>=0 ? <ArrowUpRight size={10} color={T.emerald}/> : <ArrowDownRight size={10} color={T.red}/>}
          <span style={{fontSize:8.5,fontWeight:700,color:trend>=0?T.emerald:T.red}}>
            vs B&H: {trend>=0?"+":""}{trend.toFixed(2)}%
          </span>
        </div>
      )}
    </div>
  );
}

// ── CUSTOM TOOLTIP ─────────────────────────────────────────────────────────────
function ChartTooltip({active, payload, label}) {
  if (!active || !payload?.length) return null;
  return (
    <div style={{background:T.panel,border:`1px solid ${T.border2}`,borderRadius:8,padding:"10px 13px",fontSize:9}}>
      <div style={{color:T.muted,marginBottom:6,fontWeight:800}}>{label}</div>
      {payload.map((p,i) => (
        <div key={i} style={{display:"flex",gap:8,alignItems:"center",marginBottom:3}}>
          <div style={{width:8,height:2,background:p.color,borderRadius:1}}/>
          <span style={{color:T.sub}}>{p.name}:</span>
          <span style={{color:p.color,fontWeight:900}}>₹{(+p.value).toLocaleString("en-IN",{maximumFractionDigits:0})}</span>
        </div>
      ))}
    </div>
  );
}

// ── RULE ROW ───────────────────────────────────────────────────────────────────
function RuleRow({rule, index, onChange, onDelete}) {
  const inp = {
    background:T.dim, border:`1px solid ${T.border2}`, color:T.text, borderRadius:6,
    padding:"5px 9px", fontSize:10, fontFamily:"inherit", outline:"none",
  };
  const sel = {...inp, cursor:"pointer"};
  return (
    <div style={{display:"flex",alignItems:"center",gap:8,padding:"10px 12px",
      background:T.panel,borderRadius:9,border:`1px solid ${T.border}`,
      borderLeft:`3px solid ${rule.action==="BUY"?T.emerald:T.red}`}}>
      <Badge color={rule.action==="BUY"?T.emerald:T.red} style={{fontSize:8,minWidth:36,textAlign:"center"}}>
        IF #{index+1}
      </Badge>
      <select value={rule.indicator} style={sel}
        onChange={e=>onChange(index,"indicator",e.target.value)}>
        {INDICATORS.map(i=><option key={i}>{i}</option>)}
      </select>
      <select value={rule.condition} style={{...sel,width:52}}
        onChange={e=>onChange(index,"condition",e.target.value)}>
        {CONDITIONS.map(c=><option key={c}>{c}</option>)}
      </select>
      <input type="number" value={rule.value} style={{...inp,width:72}}
        onChange={e=>onChange(index,"value",+e.target.value)}/>
      <span style={{fontSize:8.5,color:T.muted}}>THEN</span>
      <select value={rule.action} style={{...sel,
        background:rule.action==="BUY"?T.emerald+"22":T.red+"22",
        color:rule.action==="BUY"?T.emerald:T.red,
        border:`1px solid ${rule.action==="BUY"?T.emerald:T.red}55`}}
        onChange={e=>onChange(index,"action",e.target.value)}>
        {ACTIONS.map(a=><option key={a}>{a}</option>)}
      </select>
      <span style={{fontSize:7.5,color:T.muted,flex:1,opacity:0.7}}>
        {INDICATOR_DESC[rule.indicator]||""}
      </span>
      <button onClick={()=>onDelete(index)} style={{
        background:"none",border:"none",cursor:"pointer",color:T.muted,padding:4,
        display:"flex",alignItems:"center",borderRadius:4,transition:"color 0.15s"}}
        onMouseEnter={e=>e.currentTarget.style.color=T.red}
        onMouseLeave={e=>e.currentTarget.style.color=T.muted}>
        <Trash2 size={12}/>
      </button>
    </div>
  );
}

// ── MAIN COMPONENT ─────────────────────────────────────────────────────────────
export default function StrategyBacktester() {
  const [rules, setRules] = useState([
    {indicator:"RSI", condition:"<", value:35, action:"BUY"},
    {indicator:"RSI", condition:">", value:65, action:"SELL"},
  ]);
  const [activePreset, setActivePreset] = useState("RSI Oversold");
  const [running, setRunning]     = useState(false);
  const [ran, setRan]             = useState(true);
  const [showTrades, setShowTrades] = useState(false);
  const [tradeFilter, setTradeFilter] = useState("ALL");

  const result = PRESET_RESULTS[activePreset];
  const { metrics, trades, equity_curve } = result;

  const vsbuyandholdDiff = +(metrics.net_profit_pct - metrics.buy_hold_ret).toFixed(2);

  function addRule() {
    setRules(p => [...p, {indicator:"RSI",condition:"<",value:30,action:"BUY"}]);
  }
  function deleteRule(i) { setRules(p=>p.filter((_,idx)=>idx!==i)); }
  function changeRule(i, key, val) {
    setRules(p=>p.map((r,idx)=>idx===i
      ? {...r,[key]:val,...(key==="indicator"?{value:INDICATOR_DEFAULTS[val]??0}:{})}
      : r));
  }

  function loadPreset(name) {
    setActivePreset(name);
    setRules(PRESET_RESULTS[name].rules.map(r=>({...r})));
    setRan(true);
  }

  function runBacktest() {
    setRunning(true);
    setRan(false);
    // Simulate engine call — in production, replace with:
    // const res = await fetch('/api/backtest', { method:'POST', body: JSON.stringify({rules}) })
    setTimeout(() => {
      setRunning(false);
      setRan(true);
    }, 1400);
  }

  const filteredTrades = trades.filter(t =>
    tradeFilter === "ALL" || t.result === tradeFilter
  );

  const presets = Object.keys(PRESET_RESULTS);

  return (
    <div style={{padding:"18px 20px",overflowY:"auto",height:"100%",
      fontFamily:"'JetBrains Mono','IBM Plex Mono','Courier New',monospace",color:T.text}}>

      {/* ── HEADER ── */}
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:18}}>
        <div style={{display:"flex",alignItems:"center",gap:10}}>
          <div style={{width:36,height:36,background:`linear-gradient(135deg,${T.violet},${T.indigo})`,
            borderRadius:10,display:"flex",alignItems:"center",justifyContent:"center",
            boxShadow:`0 0 20px ${T.violet}44`}}>
            <FlaskConical size={18} color="#fff" strokeWidth={2.5}/>
          </div>
          <div>
            <div style={{fontSize:15,fontWeight:900,color:T.text,letterSpacing:"0.04em"}}>
              Strategy <span style={{color:T.violet}}>Backtester</span>
            </div>
            <div style={{fontSize:8,color:T.muted}}>
              RELIANCE · Jun 2023 – Mar 2024 · 252 trading days · ₹1,00,000 capital
            </div>
          </div>
        </div>
        <div style={{display:"flex",alignItems:"center",gap:6}}>
          <Badge color={T.amber}>Python Engine</Badge>
          <Badge color={T.emerald}>NSE Data</Badge>
        </div>
      </div>

      {/* ── LAYOUT: LEFT=BUILDER, RIGHT=RESULTS ── */}
      <div style={{display:"grid",gridTemplateColumns:"1fr 1.6fr",gap:14,alignItems:"start"}}>

        {/* ── LEFT: RULE BUILDER ── */}
        <div style={{display:"flex",flexDirection:"column",gap:12}}>

          {/* Preset Strategies */}
          <Card>
            <SH icon={Star} title="Preset Strategies" color={T.amber}/>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>
              {presets.map(p => {
                const m = PRESET_RESULTS[p].metrics;
                const pos = m.net_profit_pct >= 0;
                const active = activePreset === p;
                return (
                  <button key={p} onClick={()=>loadPreset(p)} style={{
                    padding:"9px 10px",borderRadius:8,cursor:"pointer",textAlign:"left",
                    fontFamily:"inherit",transition:"all 0.15s",
                    background: active ? `linear-gradient(135deg,${T.violet}22,${T.indigo}18)` : T.panel,
                    border: active ? `1px solid ${T.violet}55` : `1px solid ${T.border}`,
                  }}
                    onMouseEnter={e=>{ if(!active){ e.currentTarget.style.borderColor=T.border2; }}}
                    onMouseLeave={e=>{ if(!active){ e.currentTarget.style.borderColor=T.border; }}}>
                    <div style={{fontSize:9,fontWeight:900,color:active?T.violet:T.text,marginBottom:3}}>{p}</div>
                    <div style={{display:"flex",gap:6,alignItems:"center"}}>
                      <span style={{fontSize:10,fontWeight:900,color:pos?T.emerald:T.red}}>
                        {pos?"+":""}{m.net_profit_pct.toFixed(1)}%
                      </span>
                      <span style={{fontSize:7.5,color:T.muted}}>WR: {m.win_rate.toFixed(0)}%</span>
                    </div>
                  </button>
                );
              })}
            </div>
          </Card>

          {/* Rule Builder */}
          <Card>
            <SH icon={Target} title="Rule Builder" color={T.cyan}
              right={<Badge color={T.cyan}>{rules.length} rule{rules.length!==1?"s":""}</Badge>}/>

            <div style={{display:"flex",flexDirection:"column",gap:7,marginBottom:10}}>
              {rules.map((rule,i) => (
                <RuleRow key={i} rule={rule} index={i}
                  onChange={changeRule} onDelete={deleteRule}/>
              ))}
            </div>

            <div style={{display:"flex",gap:8}}>
              <button onClick={addRule} style={{
                flex:1,padding:"7px 0",borderRadius:7,border:`1px dashed ${T.border2}`,
                background:"transparent",color:T.muted,fontWeight:800,fontSize:9,
                cursor:"pointer",fontFamily:"inherit",display:"flex",alignItems:"center",
                justifyContent:"center",gap:5,transition:"all 0.15s"}}
                onMouseEnter={e=>{e.currentTarget.style.borderColor=T.cyan;e.currentTarget.style.color=T.cyan;}}
                onMouseLeave={e=>{e.currentTarget.style.borderColor=T.border2;e.currentTarget.style.color=T.muted;}}>
                <Plus size={11}/>ADD RULE
              </button>
              <button onClick={runBacktest} disabled={running||rules.length===0} style={{
                flex:2,padding:"7px 0",borderRadius:7,
                background:running?T.violet+"44":`linear-gradient(135deg,${T.violet},${T.indigo})`,
                border:"none",color:"#fff",fontWeight:900,fontSize:10,cursor:"pointer",
                fontFamily:"inherit",display:"flex",alignItems:"center",justifyContent:"center",gap:6,
                boxShadow:running?"none":`0 4px 18px ${T.violet}55`,
                transition:"all 0.2s",opacity:rules.length===0?0.5:1}}>
                {running ? (
                  <>
                    <div style={{width:10,height:10,borderRadius:"50%",
                      border:`2px solid #fff4`,borderTop:`2px solid #fff`,
                      animation:"spin 0.7s linear infinite"}}/>
                    RUNNING…
                  </>
                ) : (
                  <><Play size={12} fill="#fff"/>RUN BACKTEST</>
                )}
              </button>
            </div>

            {/* Logic hint */}
            <div style={{marginTop:10,padding:"8px 12px",background:T.dim,borderRadius:7,
              border:`1px solid ${T.border}`,fontSize:8,color:T.muted,lineHeight:1.7}}>
              <span style={{color:T.cyan,fontWeight:800}}>BUY</span> rules use <span style={{color:T.text}}>AND</span> logic (all must be true) ·{" "}
              <span style={{color:T.red,fontWeight:800}}>SELL</span> rules use <span style={{color:T.text}}>OR</span> logic (any triggers exit) ·{" "}
              95% capital deployed per trade · EOD execution
            </div>
          </Card>

          {/* Python engine info */}
          <Card style={{border:`1px solid ${T.indigo}33`,background:`linear-gradient(135deg,${T.indigo}0a,${T.card})`}}>
            <SH icon={Zap} title="Python Engine" color={T.indigo}/>
            <div style={{fontSize:8.5,color:T.sub,lineHeight:1.9}}>
              <div>📐 <strong style={{color:T.text}}>Indicators:</strong> RSI(14), SMA(20,50), EMA(9), MACD(12,26,9), BB(20,2)</div>
              <div>📊 <strong style={{color:T.text}}>Data:</strong> reliance_data.csv · 252 bars · OHLCV</div>
              <div>💰 <strong style={{color:T.text}}>Execution:</strong> EOD close price · 0.03% slippage</div>
              <div>🔁 <strong style={{color:T.text}}>Position:</strong> Single · 95% capital · No leverage</div>
              <div style={{marginTop:6,padding:"6px 8px",background:T.dim,borderRadius:5,fontFamily:"monospace",color:T.violet,fontSize:7.5}}>
                <div># Connect real-time engine:</div>
                <div>POST /api/backtest</div>
                <div>{"{ rules, capital, ticker }"}</div>
              </div>
            </div>
          </Card>
        </div>

        {/* ── RIGHT: RESULTS ── */}
        <div style={{display:"flex",flexDirection:"column",gap:12}}>

          {ran ? (
            <>
              {/* Metric Cards */}
              <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>
                <MetricCard
                  label="Net Profit"
                  value={`${metrics.net_profit_pct>=0?"+":""}${metrics.net_profit_pct.toFixed(2)}%`}
                  sub={`₹${metrics.net_profit.toLocaleString("en-IN",{maximumFractionDigits:0})}`}
                  color={metrics.net_profit_pct>=0?T.emerald:T.red}
                  Icon={TrendingUp}
                  trend={vsbuyandholdDiff}
                />
                <MetricCard
                  label="Win Rate"
                  value={`${metrics.win_rate.toFixed(1)}%`}
                  sub={`${metrics.wins}W · ${metrics.losses}L · ${metrics.total_trades} trades`}
                  color={metrics.win_rate>=60?T.emerald:metrics.win_rate>=40?T.amber:T.red}
                  Icon={Target}
                />
                <MetricCard
                  label="Max Drawdown"
                  value={`-${metrics.max_drawdown.toFixed(2)}%`}
                  sub={`Sharpe: ${metrics.sharpe.toFixed(3)}`}
                  color={metrics.max_drawdown<=10?T.emerald:metrics.max_drawdown<=20?T.amber:T.red}
                  Icon={Shield}
                />
              </div>

              {/* Secondary metrics */}
              <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8}}>
                {[
                  {l:"Buy & Hold",   v:`+${metrics.buy_hold_ret.toFixed(2)}%`,    c:T.cyan},
                  {l:"Profit Factor",v:metrics.profit_factor>=999?"∞":metrics.profit_factor.toFixed(3), c:metrics.profit_factor>1?T.emerald:T.red},
                  {l:"Avg Win",      v:`+₹${metrics.avg_win.toLocaleString("en-IN",{maximumFractionDigits:0})}`, c:T.emerald},
                  {l:"Avg Loss",     v:`₹${metrics.avg_loss.toLocaleString("en-IN",{maximumFractionDigits:0})}`,  c:T.red},
                ].map((m,i)=>(
                  <div key={i} style={{background:T.panel,border:`1px solid ${T.border}`,
                    borderRadius:8,padding:"8px 10px"}}>
                    <div style={{fontSize:7,color:T.muted,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:3}}>{m.l}</div>
                    <div style={{fontSize:13,fontWeight:900,color:m.c}}>{m.v}</div>
                  </div>
                ))}
              </div>

              {/* Equity Curve Chart */}
              <Card>
                <SH icon={BarChart2} title="Strategy vs Buy & Hold" color={T.cyan}
                  right={
                    <div style={{display:"flex",gap:12,fontSize:8}}>
                      <span style={{display:"flex",alignItems:"center",gap:4}}>
                        <div style={{width:16,height:2,background:T.cyan,borderRadius:1}}/>
                        Strategy
                      </span>
                      <span style={{display:"flex",alignItems:"center",gap:4}}>
                        <div style={{width:16,height:2,background:T.amber,borderRadius:1,opacity:0.7}}/>
                        Buy & Hold
                      </span>
                    </div>
                  }/>
                <ResponsiveContainer width="100%" height={220}>
                  <AreaChart data={equity_curve} margin={{top:4,right:8,bottom:0,left:0}}>
                    <defs>
                      <linearGradient id="stratGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%"  stopColor={T.cyan}  stopOpacity={0.25}/>
                        <stop offset="95%" stopColor={T.cyan}  stopOpacity={0.02}/>
                      </linearGradient>
                      <linearGradient id="bhGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%"  stopColor={T.amber} stopOpacity={0.18}/>
                        <stop offset="95%" stopColor={T.amber} stopOpacity={0.02}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="2 6" stroke={T.border} vertical={false}/>
                    <XAxis dataKey="date" tick={{fontSize:8,fill:T.muted}} axisLine={false} tickLine={false}
                      interval={3}/>
                    <YAxis tick={{fontSize:8,fill:T.muted}} axisLine={false} tickLine={false}
                      tickFormatter={v=>`₹${(v/1000).toFixed(0)}K`} domain={["auto","auto"]}/>
                    <ReferenceLine y={100000} stroke={T.muted} strokeDasharray="3 3" strokeWidth={0.7}/>
                    <Tooltip content={<ChartTooltip/>}/>
                    <Area type="monotone" dataKey="buyhold" name="Buy & Hold"
                      stroke={T.amber} strokeWidth={1.5} fill="url(#bhGrad)" strokeOpacity={0.7} dot={false}/>
                    <Area type="monotone" dataKey="strategy" name="Strategy"
                      stroke={T.cyan} strokeWidth={2} fill="url(#stratGrad)" dot={false}/>
                  </AreaChart>
                </ResponsiveContainer>
              </Card>

              {/* Win/Loss Bar */}
              <Card>
                <SH icon={Activity} title="Performance Breakdown" color={T.violet}/>
                <div style={{display:"flex",flexDirection:"column",gap:9}}>
                  {[
                    {label:"Win Rate",    value:metrics.win_rate,      max:100, color:metrics.win_rate>=60?T.emerald:T.amber},
                    {label:"Profit Factor (capped 10)",value:Math.min(metrics.profit_factor,10)/10*100,max:100,color:T.cyan,raw:metrics.profit_factor>=999?"∞":metrics.profit_factor.toFixed(2)},
                    {label:"Max Drawdown Risk",value:metrics.max_drawdown,max:50,color:metrics.max_drawdown<=10?T.emerald:metrics.max_drawdown<=20?T.amber:T.red,invert:true},
                    {label:"Strategy vs B&H",value:Math.abs(vsbuyandholdDiff),max:20,color:vsbuyandholdDiff>=0?T.emerald:T.red},
                  ].map((b,i)=>(
                    <div key={i}>
                      <div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}>
                        <span style={{fontSize:8.5,color:T.sub}}>{b.label}</span>
                        <span style={{fontSize:9,fontWeight:800,color:b.color}}>
                          {b.raw ?? `${b.invert?"-":""}${b.value.toFixed(1)}%`}
                        </span>
                      </div>
                      <MiniBar value={b.value} max={b.max} color={b.color} height={5}/>
                    </div>
                  ))}
                </div>
              </Card>

              {/* Trade Log */}
              <Card>
                <SH icon={Clock} title="Trade Log" color={T.amber}
                  right={
                    <div style={{display:"flex",alignItems:"center",gap:6}}>
                      {["ALL","WIN","LOSS"].map(f=>(
                        <button key={f} onClick={()=>setTradeFilter(f)} style={{
                          padding:"3px 9px",borderRadius:5,border:`1px solid ${tradeFilter===f?
                            (f==="WIN"?T.emerald:f==="LOSS"?T.red:T.amber)+"55":T.border}`,
                          background:tradeFilter===f?(f==="WIN"?T.emerald:f==="LOSS"?T.red:T.amber)+"18":"transparent",
                          color:tradeFilter===f?(f==="WIN"?T.emerald:f==="LOSS"?T.red:T.amber):T.muted,
                          fontWeight:800,fontSize:8,cursor:"pointer",fontFamily:"inherit"}}>
                          {f}
                        </button>
                      ))}
                      <button onClick={()=>setShowTrades(v=>!v)} style={{
                        background:"none",border:"none",cursor:"pointer",color:T.muted,
                        display:"flex",alignItems:"center"}}>
                        {showTrades?<ChevronUp size={13}/>:<ChevronDown size={13}/>}
                      </button>
                    </div>
                  }/>

                {/* Trade summary bar */}
                <div style={{display:"flex",gap:3,height:8,borderRadius:4,overflow:"hidden",marginBottom:10}}>
                  {trades.map((t,i)=>(
                    <div key={i} style={{flex:1,background:t.result==="WIN"?T.emerald:T.red,
                      borderRadius:1,transition:"opacity 0.2s",
                      opacity:tradeFilter==="ALL"||tradeFilter===t.result?1:0.2}}
                      title={`${t.entry_date} → ${t.exit_date}: ${t.result} ₹${t.pnl}`}/>
                  ))}
                </div>

                {showTrades && (
                  <div style={{animation:"fadeIn 0.2s ease"}}>
                    <table style={{width:"100%",borderCollapse:"collapse"}}>
                      <thead>
                        <tr>{["Entry","Exit","Entry ₹","Exit ₹","Shares","P&L","Result"].map(h=>(
                          <th key={h} style={{fontSize:7.5,color:T.muted,fontWeight:800,letterSpacing:"0.07em",
                            paddingBottom:7,textTransform:"uppercase",textAlign:h==="Entry"?"left":"right",
                            borderBottom:`1px solid ${T.border}`}}>{h}</th>
                        ))}</tr>
                      </thead>
                      <tbody>
                        {filteredTrades.map((t,i)=>(
                          <tr key={i}
                            onMouseEnter={e=>e.currentTarget.style.background=T.panel}
                            onMouseLeave={e=>e.currentTarget.style.background="transparent"}
                            style={{transition:"background 0.12s"}}>
                            <td style={{padding:"6px 0",borderBottom:`1px solid ${T.border}`,fontSize:8.5}}>{t.entry_date}</td>
                            <td style={{padding:"6px 8px",borderBottom:`1px solid ${T.border}`,fontSize:8.5,textAlign:"right"}}>{t.exit_date}</td>
                            <td style={{padding:"6px 8px",borderBottom:`1px solid ${T.border}`,fontSize:8.5,textAlign:"right"}}>₹{t.entry_price.toLocaleString("en-IN")}</td>
                            <td style={{padding:"6px 8px",borderBottom:`1px solid ${T.border}`,fontSize:8.5,textAlign:"right"}}>₹{t.exit_price.toLocaleString("en-IN")}</td>
                            <td style={{padding:"6px 8px",borderBottom:`1px solid ${T.border}`,fontSize:8.5,textAlign:"right",color:T.sub}}>{t.shares}</td>
                            <td style={{padding:"6px 8px",borderBottom:`1px solid ${T.border}`,fontSize:9,textAlign:"right",
                              fontWeight:900,color:t.pnl>=0?T.emerald:T.red}}>
                              {t.pnl>=0?"+":""}₹{Math.abs(t.pnl).toLocaleString("en-IN",{maximumFractionDigits:0})}
                              <span style={{fontSize:7.5,marginLeft:4,opacity:0.7}}>({t.pnl_pct>=0?"+":""}{t.pnl_pct}%)</span>
                            </td>
                            <td style={{padding:"6px 8px",borderBottom:`1px solid ${T.border}`,textAlign:"right"}}>
                              <span style={{fontSize:7.5,fontWeight:900,padding:"2px 7px",borderRadius:4,
                                background:t.result==="WIN"?T.emerald+"22":T.red+"22",
                                color:t.result==="WIN"?T.emerald:T.red,
                                border:`1px solid ${t.result==="WIN"?T.emerald:T.red}44`}}>
                                {t.result==="WIN"?"✓ WIN":"✗ LOSS"}
                              </span>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                    <div style={{marginTop:8,padding:"8px 12px",background:T.dim,borderRadius:7,
                      display:"flex",justifyContent:"space-between",fontSize:8.5}}>
                      <span style={{color:T.muted}}>Total: {filteredTrades.length} trades shown</span>
                      <span style={{color:T.emerald,fontWeight:800}}>
                        ₹{filteredTrades.filter(t=>t.pnl>0).reduce((a,t)=>a+t.pnl,0).toLocaleString("en-IN",{maximumFractionDigits:0})} gross profit
                      </span>
                      <span style={{color:T.red,fontWeight:800}}>
                        ₹{Math.abs(filteredTrades.filter(t=>t.pnl<0).reduce((a,t)=>a+t.pnl,0)).toLocaleString("en-IN",{maximumFractionDigits:0})} gross loss
                      </span>
                    </div>
                  </div>
                )}
              </Card>
            </>
          ) : (
            <div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",
              height:380,gap:14,background:T.panel,borderRadius:12,border:`1px solid ${T.border}`}}>
              <div style={{width:52,height:52,borderRadius:"50%",
                border:`3px solid ${T.violet}44`,borderTop:`3px solid ${T.violet}`,
                animation:"spin 0.8s linear infinite"}}/>
              <div style={{fontSize:11,fontWeight:900,color:T.violet}}>Running Backtest…</div>
              <div style={{fontSize:8.5,color:T.muted,textAlign:"center",maxWidth:240,lineHeight:1.7}}>
                Computing RSI · SMA · MACD · Bollinger Bands<br/>
                Simulating trades on 252 days of RELIANCE data
              </div>
            </div>
          )}
        </div>
      </div>

      <style>{`
        @keyframes fadeIn{from{opacity:0;transform:translateY(-5px)}to{opacity:1;transform:translateY(0)}}
        @keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}
      `}</style>
    </div>
  );
}
